package com.example.demo.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

// dynamoDBのテーブル名を指定
@DynamoDBTable(tableName = "Music")
public class Music {
    private String id;
    private String artist;
    private String songTitle;

    public Music() {

    }

    public Music(String artist, String songTitle) {
        this.artist = artist;
        this.songTitle = songTitle;
    }

    @DynamoDBHashKey(attributeName = "Id")
    @DynamoDBAutoGeneratedKey
    public String getId() { return id; }

    @DynamoDBAttribute
    public String getArtist() {
        return artist;
    }

    // getterにはDynamoDBAttributeアノテーションをつける
    @DynamoDBAttribute
    public String getSongTitle() {
        return songTitle;
    }

    public void setId(String id){ this.id = id; }

    public void setArtist(String artist) {
        this.artist = artist;
    }

    public void setSongTitle(String songTitle) {
        this.songTitle = songTitle;
    }

}
