package com.example.demo.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

// dynamoDBのテーブル名を指定
@DynamoDBTable(tableName = "People")
public class People {
    private String id;
    private String subId;
    private String name;

    public People() {}

    public People(String id, String subId, String name) {
        this.id = id;
        this.subId = subId;
        this.name = name;
    }

    @DynamoDBHashKey(attributeName = "Id")
    @DynamoDBAutoGeneratedKey
    public String getId() { return id; }

    @DynamoDBRangeKey(attributeName = "SubId")
    public String getSubId() {
        return subId;
    }

    // getterにはDynamoDBAttributeアノテーションをつける
    @DynamoDBAttribute(attributeName = "Name")
    public String getName() {
        return name;
    }

    public void setId(String id){ this.id = id; }

    public void setSubId(String subId) {
        this.subId = subId;
    }

    public void setName(String name) {
        this.name = name;
    }
}